name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake --preset g++-debug

    - name: Build
      run: cmake --build --preset g++-debug

    - name: Test
      run: ctest --preset g++-test-all
