name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    
    env:
      ALGO_PATH: ${{ github.workspace }}
    
    steps:
    - uses: actions/checkout@v4

    - name: check env
      run: echo $GITHUB_WORKSPACE

    - name: check ALGO_PATH
      run: echo $ALGO_PATH

    - name: Check formatting
      run: python run.py format . --check

    - name: Build
      run: python run.py build g++-debug

    - name: Test
      run: python run.py build g++-test-all

    - name: Lint
      run: python run.py lint . --preset g++-debug
