name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: check env
      run: echo $GITHUB_WORKSPACE

    - name: check pwd
      run: pwd

    - name: ls
      run: ls
    
    - name: set ALGO_PATH
      run: export ALGO_PATH=$GITHUB_WORKSPACE

    - name: Check formatting
      run: python run.py format . --check

    - name: Build
      run: python run.py build g++-debug

    - name: Test
      run: python run.py build g++-test-all

    - name: Lint
      run: python run.py lint . --preset g++-debug
