name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-24.04
    
    env:
      ALGO_PATH: ${{ github.workspace }}
    
    steps:
    - uses: actions/checkout@v4

    - name: check env
      run: echo $GITHUB_WORKSPACE

    - name: check ALGO_PATH
      run: echo $ALGO_PATH

    - name: check clang
      run: clang --version

    - name: Check formatting
      run: python run.py format algo --check && python run.py format tests --check

    - name: Build
      run: python run.py build g++-debug

    - name: Test
      run: python run.py test g++-test-all

    - name: Lint
      run: python run.py lint algo --preset g++-debug && python run.py lint tests --preset g++-debug
